
var lang_list={ 
    'ja':{	'Set_Set_Lang_0':"設定メニュー",
            'Set_Set_Lang_1':"ネットワーク設定",
            'Set_Set_Lang_2':"無線LAN起動モード設定",
            'Set_Set_Lang_3':"フォトシェア",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"管理者ではないので、このページは、アクセスできません。",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"フォトシェア",
            'Set_List_Lang_2':"フォトシェア",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"フォトシェアを解除します",
            'Set_List_Lang_6':"フォトシェアを解除しました",
            'Set_List_Lang_7':"フォトシェアを解除できませんでした",
            'Set_List_Lang_8':"フォトシェアの解除に失敗しました",
            'Set_List_Lang_9':"公開終了",
            'Set_List_Lang_10':"詳細情報:\n",
            'Set_List_Lang_11':"■ファイル名:\n",
            'Set_List_Lang_12':"■撮影日時:\n",
            'Set_List_Lang_13':"■作成日時:\n",
            'Set_List_Lang_14':"■ファイルサイズ:\n",
            'Set_List_Lang_15':"バイト\n",
            'Set_List_Lang_16':"■フォルダ名:\n",
            'Set_List_Lang_17':"フォトシェアを終了しました。",
            'Set_List_Lang_18':"元のSSIDに再接続してください。",
            'Set_List_Lang_19':"※手動起動モードに設定していた場合、無線LAN機能を再起動するには、無線LAN起動画像のプロテクトを一度ONにして再びOFFにする操作が必要です。",
    
            'Set_PicPath_Lang_0':"無線LAN起動画像",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"管理者ではないので、このページは、アクセスできません。",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"無線LAN起動モード",
            'Set_Mode_Lang_1':"自動起動モード",
            'Set_Mode_Lang_2':"タイムアウト時間",
            'Set_Mode_Lang_3':"手動起動モード",
            'Set_Mode_Lang_4':"変更" ,
            'Set_Mode_Lang_5':"１分",
            'Set_Mode_Lang_6':"３分",
            'Set_Mode_Lang_7':"５分",
            'Set_Mode_Lang_8':"１０分",
            'Set_Mode_Lang_9':"３０分",
            'Set_Mode_Lang_10':"無線LAN起動設定を変更しました。再起動してください。",
            'Set_Mode_Lang_11':"管理者ではないので、このページは、アクセスできません。",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"無線LAN起動画像",
            'Set_Mode_Lang_16':"※無線LAN起動画像に設定した画像を消去すると、無線LAN機能の起動ができなくなります。",
            'Set_Mode_Lang_17':"無線LAN起動画像を設定してください。",
            'Set_Mode_Lang_18':"No Image",
    
            'Set_FileShare_Lang_0':"フォトシェア",
            'Set_FileShare_Lang_1':"フォトシェア用SSIDに切り替えました\n",
            'Set_FileShare_Lang_2':"無線LANの接続先を\n",
            'Set_FileShare_Lang_3':"(Password:00000000)\nに変更してください\n",
            'Set_FileShare_Lang_4':"接続後、公開写真表示に切り替わります",
            'Set_FileShare_Lang_5':"フォルダ: ",
            'Set_FileShare_Lang_6':"日　　付: ",
            'Set_FileShare_Lang_7':"の写真を公開します",
            'Set_FileShare_Lang_8':"に接続してください。",
            'Set_FileShare_Lang_9':"フォトシェア設定に失敗しました",
            'Set_FileShare_Lang_10':"失敗しました。",
            'Set_FileShare_Lang_11':"管理者ではないので、このページは、アクセスできません。",
            'Set_FileShare_Lang_12':"管理者ではないので、このページは、アクセスできません。",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"ネットワーク設定",
            'Set_Config_Lang_1':"ネットワーク設定を変更しますか？\n",
            'Set_Config_Lang_2':"ネットワーク設定を変更しました。設定したSSIDに接続して下さい。",
            'Set_Config_Lang_3':"失敗しました。FlashAir設定ソフトウェアでカードの初期化を行なって下さい。",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"詳細設定",
            'Set_Config_Lang_8':"カードをフォーマットしても、同じネットワーク設定を使用する。",
            'Set_Config_Lang_9':"ネットワーク設定を初期状態に戻す。",
            'Set_Config_Lang_10':"ネットワーク設定を初期状態に変更しますか？",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"パスワードは8文字以上にしてください。",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"全ての入力欄に適切な値を指定してください。",
    
            'Set_IntroShare_Lang_0':"フォトシェア",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"以降、このページをスキップする。",
    
            'Set_IntroMode_Lang_0':"無線LAN起動モード",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"以降、このページをスキップする。",
    
            'Set_Help_Lang_Set_0':"●ネットワーク設定\n SSID/パスワードの変更を行います。\n\n",
            'Set_Help_Lang_Set_1':"●無線LAN起動モード設定\n 無線LAN起動モードを自動起動モード、手動起動モードのいずれかに設定します。\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u>無線LAN起動モードについて</u></b>",
            'Set_Help_Lang_Stmode_1':"無線LAN起動モードを選択し、「OK」ボタンを押してください。設定完了には、再起動が必要となります。",
            'Set_Help_Lang_Stmode_2':"各モードの詳細は、以下の通りです。",
            'Set_Help_Lang_Stmode_3':"■自動起動モード",
            'Set_Help_Lang_Stmode_4':"カードを挿入した機器の電源を入れると、自動的に無線LAN機能が起動するモードです。起動後、カードへ接続がない状態が、タイムアウト設定で設定された時間続くと、無線LAN機能は自動的に停止します。",
            'Set_Help_Lang_Stmode_5':"無線LAN機能を再起動させるには、カードを挿入している機器の電源を入れなおしてください。",
            'Set_Help_Lang_Stmode_6':"■手動起動モード",
            'Set_Help_Lang_Stmode_7':"デジタルカメラの画像プロテクトのON/OFF設定に連動して、無線LAN機能を停止/起動させるモードです。無線LAN機能の起動/停止に使用する画像を設定してください。デジタルカメラで、本画像のプロテクトをONにすると、無線LAN機能を停止します。本画像のプロテクトをOFFにすると、無線LAN機能を起動します。設定した画像のプロテクトの変更により、無線LAN機能の起動/停止を行いますので、デジタルカメラの電源を入れた時点で、プロテクトがOFFになっていた場合は、一度プロテクトをONにして、再度OFFにすることで、無線LAN機能を起動することができます。",
            'Set_Help_Lang_Stmode_8':"※無線LAN機能を使用しない場合は、手動起動モードに設定してください。",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u>フォトシェアについて</u></b>",
            'Set_Help_Lang_FileShare_1':"特定の日付とフォルダの写真のみを公開することができます。写真が日付とフォルダごとにグループ化されて表示されますので、①公開する写真のグループを選択して、②「OK」ボタンを押してください。",
            'Set_Help_Lang_FileShare_2':"設定が完了すると、フォトシェア用の一時的なSSID(photoshare_xxxxxxxxxxxx)とパスワード(00000000)に切り替わります。フォトシェア用のSSID/パスワードで接続した機器からは、選択した写真のみが閲覧できます。",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"無線LANを停止しますか？",
            'Set_StopWlan_Lang_2':"無線LAN機能を停止しました。"
    },
    
    'fr':{
            'Set_Set_Lang_0':"Menu Configuration",
            'Set_Set_Lang_1':"Réglages du réseau",
            'Set_Set_Lang_2':"Réglages du mode de démarrage de LAN sans fil",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"Vous ne pouvez pas accéder à cette page car vous ne disposez pas des droits d'administrateur.",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"Quitter le mode Photoshare.",
            'Set_List_Lang_6':"Mode Photoshare quitté.",
            'Set_List_Lang_7':"Impossible de quitter le mode Photoshare.",
            'Set_List_Lang_8':"Quitter le mode Photoshare a échoué.",	
            'Set_List_Lang_9':"Arrêter de partager",
            'Set_List_Lang_10':"Plus d'informations :\n",
            'Set_List_Lang_11':"- Nom de fichier :\n",
            'Set_List_Lang_12':"- Date tirée :\n",
            'Set_List_Lang_13':"- Date créée :\n",
            'Set_List_Lang_14':"- Taille de fichier : \n",
            'Set_List_Lang_15':"Octets\n",
            'Set_List_Lang_16':"- Nom de dossier :\n",
            'Set_List_Lang_17':"Mode Photoshare terminé.",
            'Set_List_Lang_18':"Reconnexion au SSID d'origine.",
            'Set_List_Lang_19':"* Si vous avez réglé le mode de démarrage manuel, vous devez protéger l'image de démarrage de LAN puis la déprotéger pour redémarrer la fonction LAN sans fil.",
    
            'Set_PicPath_Lang_0':"Image de démarrage de LAN sans fil",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"Vous ne pouvez pas accéder à cette page car vous ne disposez pas des droits d'administrateur.",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"Mode de démarrage de LAN sans fil",
            'Set_Mode_Lang_1':"Mode de démarrage automatique",
            'Set_Mode_Lang_2':"Durée de temporisation",
            'Set_Mode_Lang_3':"Mode de démarrage manuel",
            'Set_Mode_Lang_4':"Changer" ,
            'Set_Mode_Lang_5':"1 minute",
            'Set_Mode_Lang_6':"3 minutes",
            'Set_Mode_Lang_7':"5 minutes",
            'Set_Mode_Lang_8':"10 minutes",
            'Set_Mode_Lang_9':"30 minutes",
            'Set_Mode_Lang_10':"Le réglage de mode de démarrage de LAN sans fil a été modifié. Redémarrez l'appareil qui contient la carte.",
            'Set_Mode_Lang_11':"Vous ne pouvez pas accéder à cette page car vous ne disposez pas des droits d'administrateur.",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"Image de démarrage de LAN sans fil",
            'Set_Mode_Lang_16':"* Si vous supprimez l'image qui est définie en tant qu'image de démarrage de LAN sans fil, vous ne serez pas capable d'activer la fonction LAN sans fil.",
            'Set_Mode_Lang_17':"Sélectionnez une image pour la définir en tant que votre image de démarrage de LAN sans fil.",
            'Set_Mode_Lang_18':"Pas d'image",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"Passé au SSID pour le mode Photoshare.\n",
            'Set_FileShare_Lang_2':"Changez la connexion LAN sans fil sur :\n",
            'Set_FileShare_Lang_3':"(Mot de passe : 00000000)\n",
            'Set_FileShare_Lang_4':"Après la connexion, l'affichage bascule sur les photos que vous partagez.",
            'Set_FileShare_Lang_5':"Dossier : ",
            'Set_FileShare_Lang_6':"Date : ",
            'Set_FileShare_Lang_7':"Partagez les photos ci-dessus.",
            'Set_FileShare_Lang_8':"Connectez au réseau ci-dessus.",
            'Set_FileShare_Lang_9':"Échec de configuration de Photoshare.",
            'Set_FileShare_Lang_10':"Échec.",
            'Set_FileShare_Lang_11':"Vous ne pouvez pas accéder à cette page car vous ne disposez pas des droits d'administrateur.",
            'Set_FileShare_Lang_12':"Vous ne pouvez pas accéder à cette page car vous ne disposez pas des droits d'administrateur.",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"Réglages du réseau",
            'Set_Config_Lang_1':"Souhaitez-vous changer les réglages de réseau ?\n",
            'Set_Config_Lang_2':"Les réglages de réseau ont été modifiés. Connectez au SSID qui a été défini.",
            'Set_Config_Lang_3':"Échec. Veuillez initialiser la carte à l'aide du logiciel de configuration FlashAir sur un ordinateur.",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"Réglages avancés",
            'Set_Config_Lang_8':"Permet d'utiliser les mêmes réglages de réseau, même après le formatage de la carte.",
            'Set_Config_Lang_9':"Réinitialisez les réglages de réseau à leur état initial.",
            'Set_Config_Lang_10':"Souhaitez-vous modifier les réglages de réseau pour les régler sur leur état initial ?",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"Le mot de passe doit se composer d'au moins 8 caractères alphanumériques.",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"Merci de rentrer une donnée valide pour tous les paramètres.",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"À l'avenir, passez cette page.",
    
            'Set_IntroMode_Lang_0':"Mode de démarrage de LAN sans fil",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"À l'avenir, passez cette page.",
    
            'Set_Help_Lang_Set_0':"- Réglages de réseau \n Changez le SSID et le mot de passe.\n\n",
            'Set_Help_Lang_Set_1':"- Réglages mode de démarrage de LAN sans fil\n Réglez le mode de démarrage de LAN sans fil au mode de démarrage automatique ou au mode de démarrage manuel.\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;Mode de démarrage de LAN sans fil>></u></b>",
            'Set_Help_Lang_Stmode_1':"Sélectionnez le mode de démarrage de LAN sans fil et appuyez sur le bouton OK. Pour terminer le réglage, vous devez redémarrer l'appareil qui contient la carte.",
            'Set_Help_Lang_Stmode_2':"Les détails de chaque mode sont comme suit.",
            'Set_Help_Lang_Stmode_3':"- Mode de démarrage automatique",
            'Set_Help_Lang_Stmode_4':"Dans ce mode, la fonction LAN sans fil de la carte fonctionne automatiquement lorsque l'appareil détenant la carte est sous tension. S'il n'y a aucune tentative de connexion à la carte depuis un appareil (par ex. un smartphone) sur une période de temps donnée définir sous le réglage temporisation, la fonction LAN sans fil est automatiquement désactivée.",
            'Set_Help_Lang_Stmode_5':"Pour redémarrer la fonction LAN, désactivez l'appareil détenant la carte puis activez-la à nouveau.",
            'Set_Help_Lang_Stmode_6':"- Mode de démarrage manuel\n",
            'Set_Help_Lang_Stmode_7':"Dans ce mode, vous pouvez activer la fonction LAN sans fil et la désactiver en changeant le statut de protection d'écriture de la photo qui est réglé comme étant l'image de démarrage de LAN sans fil. Veuillez définir votre photo favorite en tant qu'image de démarrage de LAN. Lorsque cette photo est réglée sur déprotégée à l'aide des réglages de l'appareil, la fonction LAN sans fil est activée. Lorsqu'elle est réglée sur protégé, la fonction LAN sans fil est désactivée. Remarquez que le statut de la fonction LAN sans fil change uniuement lorsque vous changez le statut de protection d'écriture de l'image de démarrage LAN sans fil. Aussi, lorsque vous mettez l'appareil photo sous tension alors que cette photo est déprotégée, il est nécessaire de la régler sur protégé puis de la régler à nouveau sur déprotégé pour activer la fonction LAN sans fil.",
            'Set_Help_Lang_Stmode_8':"* Pour ne pas utiliser la fonction LAN sans fil, réglez le LAN sans fil sur le mode de démarrage manuel.\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"Vous pouvez uniquement partager des photos à partir d'une date et d'un dossier spécifiques. Les photos sont affichées en groupes par date et dossier. 1. Sélectionnez un groupe à partager. 2. Appuyez sur le bouton OK.",
            'Set_Help_Lang_FileShare_2':"Une fois ces réglages terminés, les réglages passent au SSID temporaire (photoshare_xxxxxxxxxxxx) et mot de passe (00000000). Seules les photos sélectionnées sont accessibles depuis les appareils connectés à l'aide du SSID et du mot de passe pour Photoshare.",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"Souhaitez-vous désactiver la fonction LAN sans fil ?",
            'Set_StopWlan_Lang_2':"La fonction LAN sans fil a été désactivée."
    },
    'it':{
            'Set_Set_Lang_0':"Menu Configurazione",
            'Set_Set_Lang_1':"Impostazioni di rete",
            'Set_Set_Lang_2':"Impostazioni modalità di avvio wireless LAN",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"Impossibile accedere alla pagina poiché non si è in possesso dei diritti di amministratore.",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"Esci dalla modalità Photoshare.",
            'Set_List_Lang_6':"Uscita modalità Photoshare effettuata.",
            'Set_List_Lang_7':"Impossibile uscire dalla modalità Photoshare.",
            'Set_List_Lang_8':"Uscita dalla modalità Photoshare fallita.",	
            'Set_List_Lang_9':"Arresta condivisione",
            'Set_List_Lang_10':"Maggiori informazioni:\n",
            'Set_List_Lang_11':"- Nome file: \n",
            'Set_List_Lang_12':"- Data istantanea:\n",
            'Set_List_Lang_13':"- Data creazione:\n",
            'Set_List_Lang_14':"- Dimensioni file: \n",
            'Set_List_Lang_15':"Byte\n",
            'Set_List_Lang_16':"- Nome cartella:\n",
            'Set_List_Lang_17':"Modalità Photoshare conclusa.",
            'Set_List_Lang_18':"Collegati di nuovo a SSID originale.",
            'Set_List_Lang_19':"* Se è stata impostata la modalità di avvio manuale si deve proteggere l'immagine di avvio della wireless LAN quindi si deve togliere la protezione e riavviare la funzione wireless LAN.",
    
            'Set_PicPath_Lang_0':"Immagine di avvio wireless LAN",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"Impossibile accedere alla pagina poiché non si è in possesso dei diritti di amministratore.",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"Modalità di avvio wireless LAN",
            'Set_Mode_Lang_1':"Modalità avvio automatico",
            'Set_Mode_Lang_2':"Tempo di timeout",
            'Set_Mode_Lang_3':"Modalità avvio manuale",
            'Set_Mode_Lang_4':"Cambia" ,
            'Set_Mode_Lang_5':"1 minuto",
            'Set_Mode_Lang_6':"3 minuti",
            'Set_Mode_Lang_7':"5 minuti",
            'Set_Mode_Lang_8':"10 minuti",
            'Set_Mode_Lang_9':"30 minuti",
            'Set_Mode_Lang_10':"L'impostazione della modalità di avvio wireless LAN è stata modificata. Riavviare il dispositivo in cui è alloggiata la scheda.",
            'Set_Mode_Lang_11':"Impossibile accedere alla pagina poiché non si è in possesso dei diritti di amministratore.",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"Immagine di avvio wireless LAN",
            'Set_Mode_Lang_16':"* Se si elimina l'immagine impostata come immagine di avvio della wireless LAN non si potrà attivare la funzione wireless LAN.",
            'Set_Mode_Lang_17':"Selezionare un'immagine da impostare come immagine di avvio della wireless LAN.",
            'Set_Mode_Lang_18':"Nessuna immagine",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"Commutato su SSID per modalità Photoshare.\n",
            'Set_FileShare_Lang_2':"Cambia la connessione wireless LAN in:\n",
            'Set_FileShare_Lang_3':"(Password: 00000000)\n",
            'Set_FileShare_Lang_4':"Dopo la connessione, il display passa alle fotografie in condivisione.",
            'Set_FileShare_Lang_5':"Cartella: ",
            'Set_FileShare_Lang_6':"Data: ",
            'Set_FileShare_Lang_7':"Condividi le fotografie precedenti.",
            'Set_FileShare_Lang_8':"Collegati alla rete precedente.",
            'Set_FileShare_Lang_9':"Impossibile configurare Photoshare.",
            'Set_FileShare_Lang_10':"Operazione fallita.",
            'Set_FileShare_Lang_11':"Impossibile accedere alla pagina poiché non si è in possesso dei diritti di amministratore.",
            'Set_FileShare_Lang_12':"Impossibile accedere alla pagina poiché non si è in possesso dei diritti di amministratore.",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"Impostazioni di rete",
            'Set_Config_Lang_1':"Cambiare le impostazioni di rete?\n",
            'Set_Config_Lang_2':"Le impostazioni di rete sono state modificate. Effettua la connessione  al SSID impostato.",
            'Set_Config_Lang_3':"Operazione fallita. Inizializzare la scheda utilizzando il software di configurazione FlashAir sul computer.",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"Impostazioni avanzate",
            'Set_Config_Lang_8':"Utilizza le stesse impostazioni di rete anche dopo la formattazione della scheda.",
            'Set_Config_Lang_9':"Ripristina le impostazioni di rete allo stato iniziale.",
            'Set_Config_Lang_10':"Cambiare le impostazioni di rete allo stato iniziale?",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"La password deve contenere almeno 8 caratteri alfanumerici.",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"Si prega di inserire un valore valido per tutte le impostazioni.",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"In futuro, salta questa pagina.",
    
            'Set_IntroMode_Lang_0':"Modalità di avvio wireless LAN",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"In futuro, salta questa pagina.",
    
            'Set_Help_Lang_Set_0':"- Impostazioni di rete \n Cambia SSID e la password.\n\n",
            'Set_Help_Lang_Set_1':"- Impostazioni modalità di avvio wireless LAN\n Imposta la modalità di avvio wireless LAN su modalità di avvio automatico o modalità di avvio manuale.\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;Modalità di avvio wireless LAN>></u></b>",
            'Set_Help_Lang_Stmode_1':"Selezionare modalità di avvio wireless LAN e premere il pulsante OK. Per completare l'impostazione, riavviare il dispositivo in cui è alloggiata la scheda.",
            'Set_Help_Lang_Stmode_2':"I dettagli di ciascuna modalità sono i seguenti.",
            'Set_Help_Lang_Stmode_3':"- Modalità avvio automatico",
            'Set_Help_Lang_Stmode_4':"In questa modalità, la funzione wireless LAN della scheda si avvia automaticamente quando si accende il dispositivo in cui è alloggiata la scheda. In assenza di tentativi di connettersi alla scheda da un dispositivo (per es. uno smartphone) entro il tempo impostato nell'impostazione di timeout, la funzione LAN si disattiva automaticamente.",
            'Set_Help_Lang_Stmode_5':"Per riavviare la funzione wireless LAN, spegnere e riaccendere il dispositivo in cui è alloggiata la scheda. ",
            'Set_Help_Lang_Stmode_6':"- Modalità avvio manuale\n",
            'Set_Help_Lang_Stmode_7':"In questa modalità si può attivare e disattivare la funzione wireless LAN modificando lo stato di protezione in scrittura della fotografia che è impostata come immagine di avvio wireless LAN. Impostare una fotografia preferita come immagine di avvio della wireless LAN. Se questa fotografia viene privata della protezione tramite le impostazioni del dispositivo, la funzione wireless LAN viene attivata. Mentre invece se essa è dotata di protezione la funzione wireless LAN viene disattivata. Si noti che lo stato della funzione wireless LAN cambia solo quando si modifica lo stato di protezione scrittura dell'immagine di avvio wireless LAN. Quando si attiva la videocamera con questa fotografia senza protezione, è necessario impostare la protezione e toglierla di nuovo per attivare la funzione wireless LAN.",
            'Set_Help_Lang_Stmode_8':"* Per non utilizzare la funzione wireless LAN, impostare wireless LAN su modalità di avvio manuale.\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"Si possono condividere solo le fotografie con una data e in una cartella specifica. Le fotografie sono visualizzate in gruppi per data e cartella. 1. Selezionare un gruppo da condividere. 2. Premere il pulsante OK.",
            'Set_Help_Lang_FileShare_2':"Al termine di queste impostazioni, le impostazioni passano al SSID temporaneo (photoshare_xxxxxxxxxxxx) e alla password (00000000). Dai dispositivi collegati utilizzando la SSID e la password per Photoshare si può accedere soltanto alle fotografie selezionate.",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"Disattivare la funzione wireless LAN?",
            'Set_StopWlan_Lang_2':"La funzione wireless LAN è stata disattivata."
    },
    'de':{
            'Set_Set_Lang_0':"Setup-Menü",
            'Set_Set_Lang_1':"Netzwerkeinstellungen",
            'Set_Set_Lang_2':"WLAN-Startmoduseinstellungen",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"Sie können diese Seite nicht aufrufen, da Sie über keine Administratorrechte verfügen.",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"Photoshare-Modus verlassen.",
            'Set_List_Lang_6':"Photoshare-Modus wurde verlassen.",
            'Set_List_Lang_7':"Photoshare-Modus konnte nicht verlassen werden.",
            'Set_List_Lang_8':"Verlassen des Photoshare-Modus fehlgeschlagen.",	
            'Set_List_Lang_9':"Teilen stoppen",
            'Set_List_Lang_10':"Weitere Informationen:\n",
            'Set_List_Lang_11':"- Dateiname:\n",
            'Set_List_Lang_12':"- Aufnahmedatum:\n",
            'Set_List_Lang_13':"- Erstellungsdatum:\n",
            'Set_List_Lang_14':"- Dateigröße: \n",
            'Set_List_Lang_15':"Bytes\n",
            'Set_List_Lang_16':"- Ordnername:\n",
            'Set_List_Lang_17':"Photoshare-Modus wurde beendet.",
            'Set_List_Lang_18':"Mit ursprünglicher SSID neu verbinden.",
            'Set_List_Lang_19':"* Wenn der manuelle Startmodus eingestellt ist, sollten Sie das WLAN-Startbild schützen und zum Neustart der WLAN-Funktion den Schutz aufheben.",
    
            'Set_PicPath_Lang_0':"WLAN-Startbild",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"Sie können diese Seite nicht aufrufen, da Sie über keine Administratorrechte verfügen.",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"WLAN-Startmodus",
            'Set_Mode_Lang_1':"Automatischer Startmodus",
            'Set_Mode_Lang_2':"Zeitabschaltungswert",
            'Set_Mode_Lang_3':"Manueller Startmodus",
            'Set_Mode_Lang_4':"Ändern" ,
            'Set_Mode_Lang_5':"1 Minute",
            'Set_Mode_Lang_6':"3 Minuten",
            'Set_Mode_Lang_7':"5 Minuten",
            'Set_Mode_Lang_8':"10 Minuten",
            'Set_Mode_Lang_9':"30 Minuten",
            'Set_Mode_Lang_10':"Die WLAN-Startmoduseinstellung wurde geändert. Starten Sie das Gerät neu, in das die Karte eingelegt ist.",
            'Set_Mode_Lang_11':"Sie können diese Seite nicht aufrufen, da Sie über keine Administratorrechte verfügen.",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"WLAN-Startbild",
            'Set_Mode_Lang_16':"* Wenn Sie das Bild löschen, welches als WLAN-Startbild eingestellt ist, können Sie die WLAN-Funktion nicht einschalten.",
            'Set_Mode_Lang_17':"Wählen Sie ein Bild als WLAN-Startbild aus.",
            'Set_Mode_Lang_18':"Kein Bild",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"Es wurde zur SSID für den Photoshare-Modus gewechselt.\n",
            'Set_FileShare_Lang_2':"Wechseln der WLAN-Verbindung zu:\n",
            'Set_FileShare_Lang_3':"(Passwort: 00000000)\n",
            'Set_FileShare_Lang_4':"Nach dem Herstellen der Verbindung wechselt die Anzeige zu den Fotos, die Sie teilen.",
            'Set_FileShare_Lang_5':"Ordner: ",
            'Set_FileShare_Lang_6':"Datum: ",
            'Set_FileShare_Lang_7':"Die oben angezeigten Fotos teilen.",
            'Set_FileShare_Lang_8':"Mit dem oben angezeigten Netzwerk verbinden.",
            'Set_FileShare_Lang_9':"Einrichten von Photoshare fehlgeschlagen.",
            'Set_FileShare_Lang_10':"Fehlgeschlagen.",
            'Set_FileShare_Lang_11':"Sie können diese Seite nicht aufrufen, da Sie über keine Administratorrechte verfügen.",
            'Set_FileShare_Lang_12':"Sie können diese Seite nicht aufrufen, da Sie über keine Administratorrechte verfügen.",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"Netzwerkeinstellungen",
            'Set_Config_Lang_1':"Möchten Sie die Netzwerkeinstellungen ändern?\n",
            'Set_Config_Lang_2':"Die Netzwerkeinstellungen wurden geändert. Mit  der eingestellten SSID verbinden.",
            'Set_Config_Lang_3':"Fehlgeschlagen. Initialisieren Sie die Karte mit der FlashAir-Konfigurationssoftware auf einem Computer.",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"Erweiterte Einstellungen",
            'Set_Config_Lang_8':"Verwenden Sie selbst nach dem Formatieren der Karte die gleichen Netzwerkeinstellungen.",
            'Set_Config_Lang_9':"Setzen Sie die Netzwerkeinstellungen in den Anfangszustand zurück.",
            'Set_Config_Lang_10':"Möchten Sie die Netzwerkeinstellungen in den Anfangszustand zurücksetzen?",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"Das Passwort sollte mindestens 8 alphanumerische Zeichen umfassen.",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"Bitte geben Sie einen gültigen Wert für alle Einstellungen ein.",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"Diese Seite zukünftig überspringen.",
    
            'Set_IntroMode_Lang_0':"WLAN-Startmodus",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"Diese Seite zukünftig überspringen.",
    
            'Set_Help_Lang_Set_0':"- Netzwerkeinstellungen \n Dient zum Ändern der SSID und des Passworts.\n\n",
            'Set_Help_Lang_Set_1':"- WLAN-Startmoduseinstellungen \n Wählen Sie zwischen dem automatischen oder manuellen WLAN-Startmodus aus.\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;WLAN-Startmodus>></u></b>",
            'Set_Help_Lang_Stmode_1':"Wählen Sie den WLAN-Startmodus und drücken Sie auf die OK-Taste. Um die Einstellung abzuschließen, müssen Sie das Gerät, in das die Karte eingelegt ist, neu starten.",
            'Set_Help_Lang_Stmode_2':"Nachfolgend finden Sie Details zu jedem Modus:",
            'Set_Help_Lang_Stmode_3':"- Automatischer Startmodus",
            'Set_Help_Lang_Stmode_4':"In diesem Modus wird die WLAN-Funktion der Karte automatisch aktiviert, wenn das Gerät, in das die Karte eingelegt ist, eingeschalten wird. Wenn ein Gerät (zum Beispiel ein Smartphone) nicht innerhalb der für die Zeitabschaltung eingestellten Zeit versucht auf die Karte zuzugreifen, deaktiviert sich die WLAN-Funktion automatisch.",
            'Set_Help_Lang_Stmode_5':"Um die WLAN-Funktion neu zu starten, schalten Sie das Gerät, in das die Karte eingelegt ist, aus und dann wieder ein.",
            'Set_Help_Lang_Stmode_6':"- Manueller Startmodus\n",
            'Set_Help_Lang_Stmode_7':"In diesem Modus kann die WLAN-Funktion aktiviert bzw. deaktiviert werden, indem der Schreibschutz des Fotos, das als WLAN-Startbild eingerichtet wurde, geändert wird. Richten Sie Ihr Lieblingsbild als WLAN-Startbild ein. Wenn der Schutz für dieses Foto über die Geräteeinstellungen aufgehoben wird, schaltet sich die WLAN-Funktion ein. Wenn der Schutz eingestellt wird, schaltet sich die WLAN-Funktion aus. Beachten Sie, dass sich der Status der WLAN-Funktion nur ändert, wenn Sie den Schreibschutzstatus des WLAN-Startbilds ändern. Wenn Sie die Kamera also einschalten, wenn dieses Foto nicht geschützt ist, muss es geschützt und der Schutz dann wieder aufgehoben werden, um die WLAN-Funktion zu aktivieren.",
            'Set_Help_Lang_Stmode_8':"* Um die WLAN-Funktion nicht zu verwenden, stellen Sie den manuellen WLAN-Startmodus ein.\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"Es können nur Fotos eines speziellen Datums oder Ordners geteilt werden. Fotos werden in Gruppen nach Datum und Ordner sortiert angezeigt. 1. Wählen Sie eine zu teilende Gruppe. 2. Drücken Sie auf die OK-Taste.",
            'Set_Help_Lang_FileShare_2':"Nach dem Abschluss dieser Einstellungen ändern sich die Einstellungen zu einer vorübergehenden SSID (photoshare_xxxxxxxxxxxx) sowie Passwort (00000000). Geräte, die über die SSID und das Passwort für Photoshare verbunden sind, können nur auf die ausgewählten Fotos zugreifen.",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"Möchten Sie die WLAN-Funktion deaktivieren?",
            'Set_StopWlan_Lang_2':"Die WLAN-Funktion wurde deaktiviert."
    },
    'es':{
            'Set_Set_Lang_0':"Menú de configuración",
            'Set_Set_Lang_1':"Configuración de red",
            'Set_Set_Lang_2':"Configuración del modo de inicio de LAN inalámbrica",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"No puede acceder a esta página porque no es administrador.",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"Abandone el modo Photoshare.",
            'Set_List_Lang_6':"Se ha abandonado el modo Photoshare.",
            'Set_List_Lang_7':"No se pudo abandonar el modo Photoshare.",
            'Set_List_Lang_8':"Se ha producido un error al abandonar el modo Photoshare.",	
            'Set_List_Lang_9':"Dejar de compartir",
            'Set_List_Lang_10':"Más información:\n",
            'Set_List_Lang_11':"- Nombre de archivo:\n",
            'Set_List_Lang_12':"- Fecha de fotografía:\n",
            'Set_List_Lang_13':"- Fecha de creación:\n",
            'Set_List_Lang_14':"- Tamaño de archivo: \n",
            'Set_List_Lang_15':"Bytes\n",
            'Set_List_Lang_16':"- Nombre de carpeta:\n",
            'Set_List_Lang_17':"Ha finalizado el modo Photoshare.",
            'Set_List_Lang_18':"Vuelva a conectarse al SSID original.",
            'Set_List_Lang_19':"* Si ha establecido el modo de inicio manual, deberá proteger la imagen de inicio de LAN inalámbrica y luego desprotegerla para reiniciar la función LAN inalámbrica.",
    
            'Set_PicPath_Lang_0':"Imagen de inicio de LAN inalámbrica",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"No puede acceder a esta página porque no es administrador.",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"Modo de inicio de LAN inalámbrica",
            'Set_Mode_Lang_1':"Modo de inicio automático",
            'Set_Mode_Lang_2':"Tiempo de espera",
            'Set_Mode_Lang_3':"Modo de inicio manual",
            'Set_Mode_Lang_4':"Cambiar" ,
            'Set_Mode_Lang_5':"1 minuto",
            'Set_Mode_Lang_6':"3 minutos",
            'Set_Mode_Lang_7':"5 minutos",
            'Set_Mode_Lang_8':"10 minutos",
            'Set_Mode_Lang_9':"30 minutos",
            'Set_Mode_Lang_10':"Se ha modificado la configuración del modo de inicio de LAN inalámbrica. Reinicie el dispositivo que contiene la tarjeta.",
            'Set_Mode_Lang_11':"No puede acceder a esta página porque no es administrador.",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"Imagen de inicio de LAN inalámbrica",
            'Set_Mode_Lang_16':"* Si borra la imagen configurada como imagen de inicio de LAN inalámbrica, no podrá activar la función LAN inalámbrica.",
            'Set_Mode_Lang_17':"Seleccione una imagen para configurarla como imagen de inicio de LAN inalámbrica.",
            'Set_Mode_Lang_18':"No hay imagen",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"Se ha cambiado al SSID para el modo Photoshare.\n",
            'Set_FileShare_Lang_2':"Cambiar la conexión LAN inalámbrica a:\n",
            'Set_FileShare_Lang_3':"(Contraseña: 00000000)\n",
            'Set_FileShare_Lang_4':"Una vez realizada la conexión, la pantalla cambia para mostrar las fotografías compartidas.",
            'Set_FileShare_Lang_5':"Carpeta: ",
            'Set_FileShare_Lang_6':"Fecha: ",
            'Set_FileShare_Lang_7':"Comparta las fotografías anteriores.",
            'Set_FileShare_Lang_8':"Conéctese a la red indicada.",
            'Set_FileShare_Lang_9':"Se ha producido un error al configurar Photoshare.",
            'Set_FileShare_Lang_10':"Se ha producido un error.",
            'Set_FileShare_Lang_11':"No puede acceder a esta página porque no es administrador.",
            'Set_FileShare_Lang_12':"No puede acceder a esta página porque no es administrador.",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"Configuración de red",
            'Set_Config_Lang_1':"¿Desea modificar la configuración de red?\n",
            'Set_Config_Lang_2':"Se ha modificado la configuración de red. Conéctese al SSID configurado.",
            'Set_Config_Lang_3':"Se ha producido un error. Inicialice la tarjeta utilizando el software de configuración de FlashAir en un ordenador.",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"Configuración avanzada",
            'Set_Config_Lang_8':"Utiliza la misma configuración de red, incluso después de formatear la tarjeta.",
            'Set_Config_Lang_9':"Reinicie la configuración de red a su estado inicial.",
            'Set_Config_Lang_10':"¿Desea cambiar la configuración de red a su estado inicial?",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"La contraseña debe tener al menos 8 caracteres alfanuméricos.",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"Por favor, introduzca un valor válido para todas las configuraciones.",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"En el futuro, sáltese esta página.",
    
            'Set_IntroMode_Lang_0':"Modo de inicio de LAN inalámbrica",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"En el futuro, sáltese esta página.",
    
            'Set_Help_Lang_Set_0':"- Configuración de red \n Cambie el SSID y la contraseña.\n\n",
            'Set_Help_Lang_Set_1':"- Configuración del modo de inicio de LAN inalámbrica\n Defina el modo de inicio de LAN inalámbrica en modo de inicio automático o manual.\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;Modo de inicio de LAN inalámbrica>></u></b>",
            'Set_Help_Lang_Stmode_1':"Seleccione el modo de inicio de LAN inalámbrica y pulse el botón Aceptar. Para completar la configuración, debe reiniciar el dispositivo que contiene la tarjeta.",
            'Set_Help_Lang_Stmode_2':"A continuación se detallan los datos de cada modo.",
            'Set_Help_Lang_Stmode_3':"- Modo de inicio automático",
            'Set_Help_Lang_Stmode_4':"En este modo, la función LAN de la tarjeta se ejecuta automáticamente al encender el dispositivo que contiene la tarjeta. Si no se produce ningún intento de conexión a la tarjeta desde un dispositivo (p.ej., un smarthpone) dentro del tiempo especificado en el ajuste de tiempo de espera, la función LAN inalámbrica se desactivará automáticamente.",
            'Set_Help_Lang_Stmode_5':"Para reiniciar la función LAN inalámbrica, apague el dispositivo que contiene la tarjeta y vuelva a encenderlo.",
            'Set_Help_Lang_Stmode_6':"- Modo de inicio manual\n",
            'Set_Help_Lang_Stmode_7':"En este modo, puede activar y desactivar la función LAN inalámbrica cambiando el estado de protección contra escritura de la fotografía configurada como imagen de inicio de LAN inalámbrica. Defina su fotografía favorita como imagen de inicio de LAN inalámbrica. Cuando dicha fotografía se ajusta en desprotegida utilizando la configuración del dispositivo, la función LAN inalámbrica se activa. Cuando se ajusta en protegida, la función LAN inalámbrica se desactiva. Observe que el estado de la función LAN inalámbrica solamente cambia cuando se modifica el estado de protección de la imagen de inicio de LAN inalámbrica. Así pues, cuando enciende la cámara con esta fotografía desprotegida, hay que ajustarla en protegida y luego en desprotegida de nuevo para activar la función LAN inalámbrica.",
            'Set_Help_Lang_Stmode_8':"* Para no utilizar la función LAN inalámbrica, defínala en modo de inicio manual.\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"Sólo puede compartir fotografías de una fecha y carpeta específicas. Los fotografías se muestran en grupos por fecha y carpeta. 1. Seleccione un grupo para compartirlo. 2. Pulso el botón Aceptar.",
            'Set_Help_Lang_FileShare_2':"Una vez finalizada la configuración, se pasa al SSID (photoshare_xxxxxxxxxxxx) y la contraseña (00000000) temporales. Sólo se puede acceder a las fotografías seleccionadas desde los dispositivos conectados utilizando el SSID y la contraseña de Photoshare.",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"¿Desea desactivar la función LAN inalámbrica?",
            'Set_StopWlan_Lang_2':"Se ha desactivado la función LAN inalámbrica."
    },
    'zh-tw':{
            'Set_Set_Lang_0':"設定選單",
            'Set_Set_Lang_1':"網路設定",
            'Set_Set_Lang_2':"無線區域網路啟動模式設定",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"您不是管理者，因此無法存取此頁面。",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"結束Photoshare模式。",
            'Set_List_Lang_6':"已結束Photoshare模式。",
            'Set_List_Lang_7':"無法結束Photoshare模式。",
            'Set_List_Lang_8':"結束Photoshare模式失敗。",	
            'Set_List_Lang_9':"停止共用",
            'Set_List_Lang_10':"其他資訊：\n",
            'Set_List_Lang_11':"- 檔案名稱\n",
            'Set_List_Lang_12':"- 拍攝日期：\n",
            'Set_List_Lang_13':"- 建立日期：\n",
            'Set_List_Lang_14':"- 檔案大小： \n",
            'Set_List_Lang_15':"位元組數\n",
            'Set_List_Lang_16':"- 資料夾名稱：\n",
            'Set_List_Lang_17':"已結束Photoshare模式。",
            'Set_List_Lang_18':"重新連接至原始SSID。",
            'Set_List_Lang_19':"* 若您已設定手動啟動模式，則應該 保護無線區域網路啟動映像檔，再加以取消保護，才能重新啟動無線區域網路功能。",
    
            'Set_PicPath_Lang_0':"無線區域網路啟動映像檔",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"您不是管理者，因此無法存取此頁面。",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"無線區域網路啟動模式",
            'Set_Mode_Lang_1':"自動啟動模式",
            'Set_Mode_Lang_2':"逾時時間",
            'Set_Mode_Lang_3':"手動啟動模式",
            'Set_Mode_Lang_4':"變更" ,
            'Set_Mode_Lang_5':"1分鐘",
            'Set_Mode_Lang_6':"3分鐘",
            'Set_Mode_Lang_7':"5分鐘",
            'Set_Mode_Lang_8':"10分鐘",
            'Set_Mode_Lang_9':"30分鐘",
            'Set_Mode_Lang_10':"已變更無線區域網路啟動模式設定。重新啟動使用卡片的裝置。",
            'Set_Mode_Lang_11':"您不是管理者，因此無法存取此頁面。",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"無線區域網路啟動映像檔",
            'Set_Mode_Lang_16':"* 若您刪除已設為無線區域網路啟動映像檔的映像檔，則會無法開啟無線區域網路功能。",
            'Set_Mode_Lang_17':"選取要設為無線區域網路啟動映像檔的映像檔。",
            'Set_Mode_Lang_18':"沒有映像檔",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"切換至Photoshare模式的SSID。\n",
            'Set_FileShare_Lang_2':"將無線區域網路連線變更為下列內容：\n",
            'Set_FileShare_Lang_3':"(密碼：00000000)\n",
            'Set_FileShare_Lang_4':"連線之後，會將顯示變更為您目前共用的照片。",
            'Set_FileShare_Lang_5':"資料夾： ",
            'Set_FileShare_Lang_6':"日期： ",
            'Set_FileShare_Lang_7':"共用上方照片。",
            'Set_FileShare_Lang_8':"連接至上方網路。",
            'Set_FileShare_Lang_9':"無法設定Photoshare。",
            'Set_FileShare_Lang_10':"失敗。",
            'Set_FileShare_Lang_11':"您不是管理者，因此無法存取此頁面。",
            'Set_FileShare_Lang_12':"您不是管理者，因此無法存取此頁面。",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"網路設定",
            'Set_Config_Lang_1':"您是否要變更網路設定？\n",
            'Set_Config_Lang_2':"已變更網路設定。連接至已設定的SSID。",
            'Set_Config_Lang_3':"失敗。請使用電腦上的FlashAir配置軟體來初始化卡片。",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"進階設定",
            'Set_Config_Lang_8':"即使已格式化卡片，還是使用相同網路設定。",
            'Set_Config_Lang_9':"將網路設定重新設為其初始狀態。",
            'Set_Config_Lang_10':"您是否要將網路設定變更為其初始狀態？",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"密碼應至少具有8個英數字元。",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"請輸入所有設置的有效值。",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"之後請跳過此頁面。",
    
            'Set_IntroMode_Lang_0':"無線區域網路啟動模式",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"之後請跳過此頁面。",
    
            'Set_Help_Lang_Set_0':"- 網路設定 \n 變更SSID及密碼。\n\n",
            'Set_Help_Lang_Set_1':"- 無線區域網路啟動模式設定\n 將無線區域網路啟動模式設為自動啟動模式或手動啟動模式。\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;無線區域網路啟動模式>></u></b>",
            'Set_Help_Lang_Stmode_1':"選取無線區域網路啟動模式並按下「確定」按鈕。若要完成設定，您必須重新啟動使用卡片的裝置。",
            'Set_Help_Lang_Stmode_2':"每一種模式的詳細資料如下所示。",
            'Set_Help_Lang_Stmode_3':"- 自動啟動模式",
            'Set_Help_Lang_Stmode_4':"在此模式下，若已開啟使用卡片的裝置，則會自動執行卡片的無線區域網路功能。若在逾時設定中所設的時間之內未嘗試從裝置 (例如，智慧型手機) 連接至卡片，則會自動關閉無線區域網路功能。",
            'Set_Help_Lang_Stmode_5':"若要重新啟動無線區域網路功能，請關閉使用裝置的卡片，然後再重新開啟。",
            'Set_Help_Lang_Stmode_6':"- 手動啟動模式\n",
            'Set_Help_Lang_Stmode_7':"在此模式下，您可以藉由變更已設為無線區域網路啟動映像檔的照片之寫入保護狀態，來開啟或關閉無線區域網路功能。請將您喜愛的照片設為無線區域網路啟動映像檔。若已使用裝置設定將此照片設為未受保護，則會開啟無線區域網路功能。若已設定為受保護，則會關閉無線區域網路功能。請注意，僅當您變更無線區域網路啟動映像檔的寫入保護狀態時，才會變更無線區域網路功能的狀態。因此，若在此照片未受保護的狀態下開啟相機，請務必將其設為受保護再重新設為未受保護，才能開啟無線區域網路功能。",
            'Set_Help_Lang_Stmode_8':"* 若不使用無線區域網路功能，請將無線區域網路設為手動啟動模式。\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"您僅能共用指定日期及資料夾的照片。照片會依日期和資料夾以群組的方式顯示。1. 選取要共用的群組。2. 按下「確定」按鈕。",
            'Set_Help_Lang_FileShare_2':"完成這些設定後，設定會變更為暫時SSID (photoshare_xxxxxxxxxxxx)及密碼(00000000)。僅有選取的照片能使用SSID及Photoshare密碼，從已連接的裝置進行存取。",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"您是否要關閉無線區域網路功能？",
            'Set_StopWlan_Lang_2':"已關閉無線區域網路功能。"
    },
    'zh-cn':{
            'Set_Set_Lang_0':"设置菜单",
            'Set_Set_Lang_1':"网络设置",
            'Set_Set_Lang_2':"无线LAN启动模式设置",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"您并非管理员，无权访问此页面。",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"退出Photoshare模式。",
            'Set_List_Lang_6':"已退出Photoshare模式。",
            'Set_List_Lang_7':"无法退出Photoshare模式。",
            'Set_List_Lang_8':"未能退出Photoshare模式。",	
            'Set_List_Lang_9':"停止同步",
            'Set_List_Lang_10':"更多信息：\n",
            'Set_List_Lang_11':"- 文件名称：\n",
            'Set_List_Lang_12':"- 拍摄日期：\n",
            'Set_List_Lang_13':"- 创建日期：\n",
            'Set_List_Lang_14':"- 文件大小： \n",
            'Set_List_Lang_15':"字节\n",
            'Set_List_Lang_16':"- 文件夹名称：\n",
            'Set_List_Lang_17':"已终止Photoshare模式。",
            'Set_List_Lang_18':"重新连接原SSID。",
            'Set_List_Lang_19':"* 如果您已设置了手动启动模式，则您应当 对无线LAN启动画面设置写保护，随后撤销写保护以便重启无线LAN功能。",
    
            'Set_PicPath_Lang_0':"无线LAN启动画面",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"您并非管理员，无权访问此页面。",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"无线LAN启动模式",
            'Set_Mode_Lang_1':"自动启动模式",
            'Set_Mode_Lang_2':"超时时间",
            'Set_Mode_Lang_3':"手动启动模式",
            'Set_Mode_Lang_4':"更改" ,
            'Set_Mode_Lang_5':"1分钟",
            'Set_Mode_Lang_6':"3分钟",
            'Set_Mode_Lang_7':"5分钟",
            'Set_Mode_Lang_8':"10分钟",
            'Set_Mode_Lang_9':"30分钟",
            'Set_Mode_Lang_10':"无线LAN启动模式设置已更改。重启插卡设备。",
            'Set_Mode_Lang_11':"您并非管理员，无权访问此页面。",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"无线LAN启动画面",
            'Set_Mode_Lang_16':"* 如果您检测到了被设置为无线LAN启动画面的图像，则无法开启无线LAN功能。",
            'Set_Mode_Lang_17':"选择一张设置为您的无线LAN启动画面的图像。",
            'Set_Mode_Lang_18':"无图像",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"SSID已切换至Photoshare模式。\n",
            'Set_FileShare_Lang_2':"将无线LAN连接更改为：\n",
            'Set_FileShare_Lang_3':"（密码：00000000）\n",
            'Set_FileShare_Lang_4':"连接之后，显示屏切换至您正在同步的照片。",
            'Set_FileShare_Lang_5':"文件夹： ",
            'Set_FileShare_Lang_6':"日期： ",
            'Set_FileShare_Lang_7':"同步上述照片。",
            'Set_FileShare_Lang_8':"连接至上述网络。",
            'Set_FileShare_Lang_9':"设置Photoshare失败。",
            'Set_FileShare_Lang_10':"失败。",
            'Set_FileShare_Lang_11':"您并非管理员，无权访问此页面。",
            'Set_FileShare_Lang_12':"您并非管理员，无权访问此页面。",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"网络设置",
            'Set_Config_Lang_1':"是否要更改网络设置？\n",
            'Set_Config_Lang_2':"网络设置已更改。连接至之前设置的 SSID。",
            'Set_Config_Lang_3':"失败。请使用计算机上的FlashAir配置软件初始化存储卡。",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"高级设置",
            'Set_Config_Lang_8':"使用相同的网络设置，即便存储卡已格式化。",
            'Set_Config_Lang_9':"重置网络设置至初始状态。",
            'Set_Config_Lang_10':"是否将网络设置更改为初始状态？",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"密码至少包含8个字母数字字符。",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"请输入所有设置的有效值。",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"未来可忽略这一页。",
    
            'Set_IntroMode_Lang_0':"无线LAN启动模式",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"未来可忽略这一页。",
    
            'Set_Help_Lang_Set_0':"- 网络设置 \n 更改SSID和密码。\n\n",
            'Set_Help_Lang_Set_1':"- 无线LAN启动模式设置\n 将无线LAN启动模式设置为自动启动模式或手动设置模式。\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;无线LAN启动模式>></u></b>",
            'Set_Help_Lang_Stmode_1':"选择无线LAN启动模式，然后按下OK按钮。想要完成设置，必须重启插卡设备。",
            'Set_Help_Lang_Stmode_2':"各种模式的详细信息如下。",
            'Set_Help_Lang_Stmode_3':"- 自动启动模式",
            'Set_Help_Lang_Stmode_4':"在此模式下，插卡设备启动后，存储卡的无线LAN功能自动运行。如果未在设定的超时设置时间内常识连接设备（如智能手机）上的存储卡，则无线LAN功能自动关闭。",
            'Set_Help_Lang_Stmode_5':"如要重启无线LAN功能，须先关闭然后重新开启插卡设备。",
            'Set_Help_Lang_Stmode_6':"- 手动启动模式\n",
            'Set_Help_Lang_Stmode_7':"在此模式下，您可以更改被设置为无线LAN启动画面的照片的写保护状态，从而开关无线LAN功能。请将您所中意的照片设为无线LAN启动画面。如果通过设备设置将此照片设为非保护状态，则无线LAN功能开启。如果设为写保护状态，则无线LAN功能关闭。请注意，仅在无线LAN启动画面的写保护状态更改时，无线LAN功能才会才会切换。因此，当您开启带有此无保护照片的相机时，必须将其设为写保护状态，并在随后再次将其设为无保护状态以便开启无线LAN功能。",
            'Set_Help_Lang_Stmode_8':"* 如果不使用无线LAN功能，则将无线LAN设置为手动启动模式。\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"您仅可同步特定日期和文件夹下的照片。照片将按照日期和文件夹分组显示。1. 选择一组照片同步。2. 按下 OK 按钮。",
            'Set_Help_Lang_FileShare_2':"此类设置完成后，设置更改为临时SSID(photoshare_xxxxxxxxxxxx)和密码(00000000)。使用Photoshare的SSID和密码时，仅可通过所连设备访问选定的照片。",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"是否想要关闭无线LAN功能？",
            'Set_StopWlan_Lang_2':"无线LAN功能已关闭。"
    },
    'ko':{
            'Set_Set_Lang_0':"설정 메뉴",
            'Set_Set_Lang_1':"네트워크 설정",
            'Set_Set_Lang_2':"무선 LAN 시작 모드 설정",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"관리자가 아니므로 이 페이지에 접근할 수 없습니다.",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"Photoshare 모드를 종료하십시오.",
            'Set_List_Lang_6':"Photoshare 모드가 종료되었습니다.",
            'Set_List_Lang_7':"Photoshare 모드를 종료할 수 없습니다.",
            'Set_List_Lang_8':"Photoshare 모드를 종료하지 못했습니다.",	
            'Set_List_Lang_9':"공유 중지",
            'Set_List_Lang_10':"추가 정보:\n",
            'Set_List_Lang_11':"- 파일 이름:\n",
            'Set_List_Lang_12':"- 촬영 날짜:\n",
            'Set_List_Lang_13':"- 만든 날짜:\n",
            'Set_List_Lang_14':"- 파일 크기: \n",
            'Set_List_Lang_15':"바이트\n",
            'Set_List_Lang_16':"- 폴더 이름:\n",
            'Set_List_Lang_17':"Photoshare 모드가 종료되었습니다.",
            'Set_List_Lang_18':"원래 SSID에 다시 연결하십시오.",
            'Set_List_Lang_19':"* 수동 시작 모드를 설정한 경우, 무선 LAN 시작 이미지를 보호한 후 보호를 취소하여 무선 LAN 기능을 다시 시작해야 합니다.",
    
            'Set_PicPath_Lang_0':"무선 LAN 시작 이미지",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"관리자가 아니므로 이 페이지에 접근할 수 없습니다.",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"무선 LAN 시작 모드",
            'Set_Mode_Lang_1':"자동 시작 모드",
            'Set_Mode_Lang_2':"제한 시간",
            'Set_Mode_Lang_3':"수동 시작 모드",
            'Set_Mode_Lang_4':"변경" ,
            'Set_Mode_Lang_5':"1분",
            'Set_Mode_Lang_6':"3분",
            'Set_Mode_Lang_7':"5분",
            'Set_Mode_Lang_8':"10분",
            'Set_Mode_Lang_9':"30분",
            'Set_Mode_Lang_10':"무선 LAN 시작 모드 설정이 변경되었습니다. 카드가 들어 있는 장치를 다시 시작하십시오.",
            'Set_Mode_Lang_11':"관리자가 아니므로 이 페이지에 접근할 수 없습니다.",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"무선 LAN 시작 이미지",
            'Set_Mode_Lang_16':"* 무선 LAN 시작 이미지로 설정된 이미지를 삭제하면 무선 LAN 기능을 설정할 수 없게 됩니다.",
            'Set_Mode_Lang_17':"무선 LAN 시작 이미지로 설정할 이미지를 선택하십시오.",
            'Set_Mode_Lang_18':"이미지 없음",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"Photoshare용 SSID 모드로 전환되었습니다.\n",
            'Set_FileShare_Lang_2':"무선 LAN 연결 변경 대상:\n",
            'Set_FileShare_Lang_3':"(암호: 00000000)\n",
            'Set_FileShare_Lang_4':"연결 후 디스플레이가 공유 중인 사진으로 바뀝니다.",
            'Set_FileShare_Lang_5':"폴더:  ",
            'Set_FileShare_Lang_6':"날짜:  ",
            'Set_FileShare_Lang_7':"위의 사진을 공유합니다.",
            'Set_FileShare_Lang_8':"위의 네트워크에 연결합니다.",
            'Set_FileShare_Lang_9':"Photoshare를 설정하지 못했습니다.",
            'Set_FileShare_Lang_10':"실패했습니다.",
            'Set_FileShare_Lang_11':"관리자가 아니므로 이 페이지에 접근할 수 없습니다.",
            'Set_FileShare_Lang_12':"관리자가 아니므로 이 페이지에 접근할 수 없습니다.",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"네트워크 설정",
            'Set_Config_Lang_1':"네트워크 설정을 변경하시겠습니까?\n",
            'Set_Config_Lang_2':"네트워크 설정이 변경되었습니다. 설정한 SSID에 연결하십시오.",
            'Set_Config_Lang_3':"실패했습니다. 컴퓨터에서 FlashAir 구성 소프트웨어를 사용하여 카드를 초기화하십시오.",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"고급 설정",
            'Set_Config_Lang_8':"카드를 포맷한 후에도 동일한 네트워크 설정을 사용합니다.",
            'Set_Config_Lang_9':"네트워크 설정을 초기 상태로 재설정합니다.",
            'Set_Config_Lang_10':"네트워크 설정을 초기 상태로 변경하시겠습니까?",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"암호는 최소 8자 이상의 영숫자 문자여야 합니다.",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"모든 설정에 올바른 값을 입력하십시오.",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"나중에 이 페이지를 건너뛰십시오.",
    
            'Set_IntroMode_Lang_0':"무선 LAN 시작 모드",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"나중에 이 페이지를 건너뛰십시오.",
    
            'Set_Help_Lang_Set_0':"- 네트워크 설정 \n SSID 및 암호를 변경하십시오.\n\n",
            'Set_Help_Lang_Set_1':"- 무선 LAN 시작 모드 설정\n 무선 LAN 시작 모드를 자동 시작 모드 또는 수동 시작 모드로 설정합니다.\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;무선 LAN 시작 모드>></u></b>",
            'Set_Help_Lang_Stmode_1':"무선 LAN 시작 모드를 선택하고 확인 버튼을 누르십시오. 설정을 완료하려면 카드가 들어 있는 장치를 다시 시작해야 합니다.",
            'Set_Help_Lang_Stmode_2':"각 모드의 세부 정보는 다음과 같습니다.",
            'Set_Help_Lang_Stmode_3':"- 자동 시작 모드",
            'Set_Help_Lang_Stmode_4':"이 모드에서는 카드가 들어 있는 장치가 켜지면 카드의 무선 LAN 기능이 자동으로 실행됩니다. 제한 시간 설정에서 지정된 시간 내에 장치(예: 스마트폰)에서 카드 연결 시도가 없을 경우, 무선 LAN 기능이 자동으로 꺼집니다.",
            'Set_Help_Lang_Stmode_5':"무선 LAN 기능을 다시 시작하려면 카드가 들어 있는 장치를 껐다가 다시 켜십시오. ",
            'Set_Help_Lang_Stmode_6':"- 수동 시작 모드\n",
            'Set_Help_Lang_Stmode_7':"이 모드에서는 무선 LAN 시작 이미지로 설정된 사진의 쓰기 보호 상태를 변경하여 무선 LAN 기능을 켜고 끌 수 있습니다. 즐겨 이용하는 사진을 무선 LAN 시작 이미지로 설정하십시오. 이 사진이 장치의 설정을 사용하여 보호 취소 상태로 설정되면 무선 LAN 기능이 켜집니다. 보호 상태로 설정되면 무선 LAN 기능이 꺼집니다. 무선 LAN 기능의 상태는 무선 LAN 시작 이미지의 쓰기 보호 상태를 변경한 경우에만 변경된다는 점을 유념하십시오. 따라서 이 사진이 보호되지 않은 상태로 카메라를 켠 경우에는 보호 상태로 설정했다가 다시 보호를 취소해야 무선 LAN 기능이 켜집니다.",
            'Set_Help_Lang_Stmode_8':"* 무선 LAN 기능을 사용하지 않으려면 무선 LAN을 수동 시작 모드로 설정하십시오.\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"특정 날짜와 폴더의 사진만 공유할 수 있습니다. 사진은 날짜와 폴더별로 그룹에 표시됩니다. 1. 공유할 그룹을 선택하십시오. 2. 확인 버튼을 누르십시오.",
            'Set_Help_Lang_FileShare_2':"이러한 설정이 완료되면 해당 설정이 임시 SSID(photoshare_xxxxxxxxxxxx) 및 암호(00000000)로 바뀝니다. Photoshare용 SSID와 암호를 사용하여 연결된 장치에서만 선택한 사진에 액세스할 수 있습니다.",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"무선 LAN 기능을 끄시겠습니까?",
            'Set_StopWlan_Lang_2':"무선 LAN 기능이 꺼졌습니다."
    },
    
    'en':{
            'Set_Set_Lang_0':"Setup menu",
            'Set_Set_Lang_1':"Network settings",
            'Set_Set_Lang_2':"Wireless LAN startup mode settings",
            'Set_Set_Lang_3':"Photoshare",
            'Set_Set_Lang_4':"",
            'Set_Set_Lang_5':"",
            'Set_Set_Lang_6':"You cannot access this page because you are not an administrator.",
    
            'Set_List_Lang_0':"",
            'Set_List_Lang_1':"Photoshare",
            'Set_List_Lang_2':"Photoshare",
            'Set_List_Lang_3':"",
            'Set_List_Lang_4':"",
            'Set_List_Lang_5':"Exit Photoshare mode.",
            'Set_List_Lang_6':"Photoshare mode exited.",
            'Set_List_Lang_7':"Could not exit Photoshare mode.",
            'Set_List_Lang_8':"Failed to exit Photoshare mode.",	
            'Set_List_Lang_9':"Stop sharing",
            'Set_List_Lang_10':"More information :\n",
            'Set_List_Lang_11':"- File name:\n",
            'Set_List_Lang_12':"- Date shot:\n",
            'Set_List_Lang_13':"- Date created:\n",
            'Set_List_Lang_14':"- File size: \n",
            'Set_List_Lang_15':"Bytes\n",
            'Set_List_Lang_16':"- Folder name:\n",
            'Set_List_Lang_17':"Photoshare mode ended.",
            'Set_List_Lang_18':"Re-connect to original SSID.",
            'Set_List_Lang_19':"* If you have set manual startup mode, you should protect the wireless LAN startup image and then unprotect it to re-start the wireless LAN function.",
    
            'Set_PicPath_Lang_0':"Wireless LAN startup image",
            'Set_PicPath_Lang_1':"",
            'Set_PicPath_Lang_2':"",
            'Set_PicPath_Lang_3':"You cannot access this page because you are not an administrator.",
            'Set_PicPath_Lang_4':"",
            'Set_PicPath_Lang_5':"",
            'Set_PicPath_Lang_6':"OK",
    
            'Set_Mode_Lang_0':"Wireless LAN startup mode",
            'Set_Mode_Lang_1':"Automatic startup mode",
            'Set_Mode_Lang_2':"Timeout time",
            'Set_Mode_Lang_3':"Manual startup mode",
            'Set_Mode_Lang_4':"Change" ,
            'Set_Mode_Lang_5':"1minute",
            'Set_Mode_Lang_6':"3minutes",
            'Set_Mode_Lang_7':"5minutes",
            'Set_Mode_Lang_8':"10minutes",
            'Set_Mode_Lang_9':"30minutes",
            'Set_Mode_Lang_10':"Wireless LAN startup mode setting was changed. Restart the device that is holding the card.",
            'Set_Mode_Lang_11':"You cannot access this page because you are not an administrator.",
            'Set_Mode_Lang_12':"",
            'Set_Mode_Lang_13':"",
            'Set_Mode_Lang_14':"OK",
            'Set_Mode_Lang_15':"Wireless LAN startup image",
            'Set_Mode_Lang_16':"* If you delete the image which is set as the wireless LAN startup image, you will not be able to turn on the wireless LAN function.",
            'Set_Mode_Lang_17':"Select an image to set as your wireless LAN startup image.",
            'Set_Mode_Lang_18':"No image",
    
            'Set_FileShare_Lang_0':"Photoshare",
            'Set_FileShare_Lang_1':"Switched to SSID for Photoshare mode.\n",
            'Set_FileShare_Lang_2':"Change the wireless LAN connection to:\n",
            'Set_FileShare_Lang_3':"(Password:00000000)\n",
            'Set_FileShare_Lang_4':"After connection, the display changes to the photos you are sharing.",
            'Set_FileShare_Lang_5':"Folder: ",
            'Set_FileShare_Lang_6':"Date: ",
            'Set_FileShare_Lang_7':"Share the above photos.",
            'Set_FileShare_Lang_8':"Connect to the above network.",
            'Set_FileShare_Lang_9':"Failed to set up Photoshare.",
            'Set_FileShare_Lang_10':"Failed.",
            'Set_FileShare_Lang_11':"You cannot access this page because you are not an administrator.",
            'Set_FileShare_Lang_12':"You cannot access this page because you are not an administrator.",
            'Set_FileShare_Lang_13':"",
            'Set_FileShare_Lang_14':"OK",
    
            'Set_Config_Lang_0':"Network settings",
            'Set_Config_Lang_1':"Do you want to change the network settings?\n",
            'Set_Config_Lang_2':"Network settings were changed. Connect to the SSID that was set.",
            'Set_Config_Lang_3':"Failed. Please initialize the card using FlashAir Configuration Software on a computer.",
            'Set_Config_Lang_4':"",
            'Set_Config_Lang_5':"",
            'Set_Config_Lang_6':"OK",
            'Set_Config_Lang_7':"Advanced settings",
            'Set_Config_Lang_8':"Uses the same network settings, even after the card is formatted.",
            'Set_Config_Lang_9':"Reset the network settings to their initial state.",
            'Set_Config_Lang_10':"Do you want to change the network settings to their initial state?",
            'Set_Config_Lang_11':"Password:",
            'Set_Config_Lang_12':"Password should have at least 8 alphanumeric characters.",
            'Set_Config_Lang_13':"SSID:",
            'Set_Config_Lang_14':"Please input a valid value for all settings.",
    
            'Set_IntroShare_Lang_0':"Photoshare",
            'Set_IntroShare_Lang_1':"",
            'Set_IntroShare_Lang_2':"",
            'Set_IntroShare_Lang_3':"In the future, skip this page.",
    
            'Set_IntroMode_Lang_0':"Wireless LAN startup mode",
            'Set_IntroMode_Lang_1':"",
            'Set_IntroMode_Lang_2':"",
            'Set_IntroMode_Lang_3':"In the future, skip this page.",
    
            'Set_Help_Lang_Set_0':"- Network Settings \n Change the SSID and password.\n\n",
            'Set_Help_Lang_Set_1':"- Wireless LAN startup mode settings\n Set the wireless LAN startup mode to automatic startup mode or manual startup mode.\n\n",
            'Set_Help_Lang_Set_2':"",
            'Set_Help_Lang_Set_3':"",
            'Set_Help_Lang_Set_4':"",
            'Set_Help_Lang_Set_5':"",
            'Set_Help_Lang_Set_6':"",
            'Set_Help_Lang_Set_7':"",
            'Set_Help_Lang_Set_8':"",
            'Set_Help_Lang_Set_9':"",
    
            'Set_Help_Lang_Stmode_0':"<b><u><&lt;Wireless LAN startup mode>></u></b>",
            'Set_Help_Lang_Stmode_1':"Select wireless LAN startup mode and push the OK button. To complete the setting, you must restart the device that is holding the card.",
            'Set_Help_Lang_Stmode_2':"The details of each mode are as follows.",
            'Set_Help_Lang_Stmode_3':"- Automatic startup mode",
            'Set_Help_Lang_Stmode_4':"In this mode, the wireless LAN function of the card runs automatically when the device holding the card is turned on. If there is no attempt to connect to the card from a device (e.g. a smartphone) within the time set in the timeout setting, the wireless LAN function automatically turns off.",
            'Set_Help_Lang_Stmode_5':"To restart the wireless LAN function, turn off the device holding the card and then turn it on again. ",
            'Set_Help_Lang_Stmode_6':"- Manual startup mode\n",
            'Set_Help_Lang_Stmode_7':"In this mode, you can turn the wireless LAN function on and off by changing the write protection status of the photo which is set as the wireless LAN startup image. Please set your favorite photo as the wireless LAN startup image. When this photo is set to unprotected using the device’s settings, the wireless LAN function is turned on. When it is set to protected, the wireless LAN function is turned off. Note that the status of the wireless LAN function changes only when you change the write protection status of the wireless LAN startup image. So, when you turn on the camera with this photo unprotected, it is necessary to set it to protected and then set it to unprotected again to turn on the wireless LAN function.",
            'Set_Help_Lang_Stmode_8':"* To not use the wireless LAN function, set the wireless LAN to manual startup mode.\n\n",
            'Set_Help_Lang_Stmode_9':"",
    
            'Set_Help_Lang_FileShare_0':"<b><u><&lt;Photoshare>></u></b>\n\n",
            'Set_Help_Lang_FileShare_1':"You can share only photos from a specific date and folder. Photos are displayed in groups by date and folder. 1. Select a group to share. 2. Push the OK button.",
            'Set_Help_Lang_FileShare_2':"After these settings are finished, the settings change to the temporary SSID (photoshare_xxxxxxxxxxxx) and password (00000000). Only the selected photos can be accessed from devices connected using the SSID and password for Photoshare.",
            'Set_Help_Lang_FileShare_3':"",
            'Set_Help_Lang_FileShare_4':"",
            'Set_Help_Lang_FileShare_5':"",
            'Set_Help_Lang_FileShare_6':"",
            'Set_Help_Lang_FileShare_7':"",
            'Set_Help_Lang_FileShare_8':"",
            'Set_Help_Lang_FileShare_9':"",
    
            'Set_StopWlan_Lang_1':"Do you want to turn off the wireless LAN function?",
            'Set_StopWlan_Lang_2':"The wireless LAN function was turned off."
    }
    
    }
    
    
    